package com.ancun.lib;

/**
 * desc:
 * date: 2018/3/23
 * author: ancun
 */

public class hh {

    //    a : EtapLib
    //    b : checkManifestIsOK:
    //    c : pls config
    //    d :  in manifest.xml
    //    e : checkManifestIsOK:
    //    f : pls config
    //    g :  in manifest.xml
    //    h : 320x200
    //    i : 480x800
    //    j : 640x100
    //    k : 1200x627
    //    l : View
    //    m : AdUtil
    //    n : VIEW_SHOW
    //    o : WIFI
    //    p : 2g
    //    q : 3g
    //    r : 4g
    //    s : unknown
    //    t : etap_update_file_latest
    //    u : etap_dynamic_update_time
    //    v : etap_google_advertisingId
    //    w : sharedpreferences_etap_settings
    //    x : ro.yunos.model
    //    y : android.os.SystemProperties
    //    z : get
    //    A : /proc/meminfo
    //    B : \s+
    //    C : x
    //    D : GPRS
    //    E : EDGE
    //    F : CDMA
    //    G : 1xRTT
    //    H : IDEN
    //    I : UMTS
    //    J : EVDO0
    //    K : EVDOA
    //    L : HSUPA
    //    M : HSUPA
    //    N : HSPA
    //    O : EVDOB
    //    P : EHRPD
    //    Q : HSPAP
    //    R : LTE
    //    S : GSM
    //    T : %s_%s
    //    U : http.agent
    //    V : 0.0
    //    W : 0.0
    //    X : wfdkg
    //    Y : wfswl
    //    Z : kgr
    //    aA : EtapAdType required
    //    aB : sorry,our server too tired.
    //    aC : all ads comsumed
    //    aD : illegal placement_id
    //    aE : request too frequently
    //    aF : ad is not ready or already displayed
    //    aG : placement type error
    //    aH : etap_extra_iactivity_class_name
    //    aI : etap_extra_iactivity_key
    //    aJ : EtapBanner
    //    aK : Subject_RedirectStrategy
    //    aL : campid
    //    aM : pkgname
    //    aN : redirect_url
    //    aO : ms_url
    //    aP : aid
    //    aQ : gaid
    //    aR : value
    //    aS : UTF-8
    //    aT : 30a161c4b1bde4eea
    //    aU : 30a161c4b1bde4eea
    //    aV : data
    //    aW : pkey
    //    aX : zz2017
    //    aY : sign
    //    aZ : DspHelper
    //    aa : 1
    //    ab : true
    //    ac : wfdkg
    //    ad : wfswl
    //    ae : 1
    //    af : kgr
    //    ag : true
    //    ah : kgr
    //    ai : wt
    //    aj : 1
    //    ak : 0
    //    al : wfdkg
    //    am : 1
    //    an : 0
    //    ao : wfswl
    //    ap : Cannot be called from the main thread
    //    aq : com.android.vending
    //    ar : com.google.android.gms.ads.identifier.service.START
    //    as : com.google.android.gms
    //    at : Google Play connection failed
    //    au : com.google.android.gms.ads.identifier.internal.IAdvertisingIdService
    //    av : com.google.android.gms.ads.identifier.internal.IAdvertisingIdService
    //    aw : no network.
    //    ax : no offers.
    //    ay : no material.
    //    az : appkey required.
    //    bA : X-Requested-With
    //    bB : text/plain
    //    bC : ;
    //    bD : Access-Control-Allow-Origin
    //    bE : Access-Control-Allow-Origin
    //    bF : *
    //    bG : Access-Control-Allow-Methods
    //    bH : Access-Control-Allow-Methods
    //    bI : GET,HEAD,POST,PUT,DELETE
    //    bJ : OK
    //    bK : res_status
    //    bL : save_time
    //    bM : valid_time
    //    bN : resp_code
    //    bO : resp_msg
    //    bP : req_id
    //    bQ : z
    //    bR : body
    //    bS : 30a161c4b1bde4eea
    //    bT : id
    //    bU : pSwitch
    //    bV : pkg
    //    bW : offer
    //    bX : stat
    //    bY : offerc
    //    bZ : cache
    //    ba : #00ffffff
    //    bb : text/html
    //    bc : utf-8
    //    bd : text/html
    //    be : utf-8
    //    bf : text/javascript
    //    bg : ;
    //    bh : ;
    //    bi : =
    //    bj : charset
    //    bk : utf-8
    //    bl : utf-8
    //    bm : text/html
    //    bn : utf-8
    //    bo : Set-Cookie
    //    bp : Set-Cookie
    //    bq : Set-Cookie
    //    br : Content-Type
    //    bs : text/plain
    //    bt : Content-Length
    //    bu : utf-8
    //    bv : https
    //    bw : TLSv1
    //    bx : http
    //    by : GET
    //    bz : User-Agent
    //    cA : secure
    //    cB : path
    //    cC : max-age
    //    cD : unknown.com
    //    cE : |
    //    cF : iso-8859-1
    //    cG : iso-8859-1
    //    cH : utf-8
    //    cI : utf-8
    //    cJ : utf-8
    //    cK : utf-8
    //    cL : Base64OperationStatisti
    //    cM : |
    //    cN : BatMobi_2016
    //    cO : utf-8
    //    cP : |
    //    cQ : |
    //    cR : 2
    //    cS : 2
    //    cT : 2
    //    cU : 2
    //    cV : -1
    //    cW : |
    //    cX : |
    //    cY : |
    //    cZ : |
    //    ca : html
    //    cb : click_url
    //    cc : click_callback_url
    //    cd : click_route
    //    ce : appid
    //    cf : nlg
    //    cg : fp
    //    ch : request_url
    //    ci : imp_url
    //    cj : prl
    //    ck : cacheTime
    //    cl : data
    //    cm : start
    //    cn : end
    //    co : NoSSLv3SocketFactory
    //    cp : SSLv3
    //    cq : SSLv3
    //    cr : dsp_h5_ad
    //    cs : 2
    //    ct : 2
    //    cu : save_time
    //    cv : valid_time
    //    cw : :\\^#
    //    cx : ([^;\s]+)\s*=\s*([^;\s]+)
    //    cy : domain
    //    cz : expires
    //    dA : pkg=?
    //    dB : record_time<?
    //    dC : 10
    //    dD : failed
    //    dE : pkg=?
    //    dF : BatMobi_2016
    //    dG : utf-8
    //    dH : ps.db
    //    dI : ps
    //    dJ : uuid
    //    dK : pkg
    //    dL : ad
    //    dM : f_name
    //    dN : d_time
    //    dO : req_time
    //    dP : res_time
    //    dQ : server_res_time
    //    dR : res_result
    //    dS : p_start
    //    dT : p_finish
    //    dU : result
    //    dV : rf
    //    dW : error_msg
    //    dX : delayed_time
    //    dY : rf_time
    //    dZ : i_time
    //    da : |
    //    db : |
    //    dc : |
    //    dd : |
    //    de : |
    //    df : |
    //    dg : |
    //    dh : |
    //    di : |
    //    dj : |
    //    dk : |
    //    dl : |
    //    dm : |
    //    dn : |
    //    dp : |
    //    dq : |
    //    dr : |
    //    ds : |
    //    dt : |
    //    du : PreDBManager
    //    dv : pkg
    //    dw : pkg=?
    //    dx : pkg=?
    //    dy : uuid
    //    dz : record_time
    //    eA :  TEXT,
    //    eB :  TEXT,
    //    eC :  TEXT,
    //    eD :  TEXT,
    //    eE :  TEXT,
    //    eF :  TEXT,
    //    eG :  TEXT,
    //    eH :  TEXT,
    //    eI :  TEXT,
    //    eJ :  TEXT,
    //    eK :  TEXT,
    //    eL :  TEXT,
    //    eM :  INTEGER)
    //    eN : alter table
    //    eO :  add column
    //    eP :  TEXT
    //    eQ : alter table
    //    eR :  add column
    //    eS :  TEXT
    //    eT : alter table
    //    eU :  add column
    //    eV :  TEXT
    //    eW : alter table
    //    eX :  add column
    //    eY :  TEXT
    //    eZ : RemoteLog
    //    ea : service_id
    //    eb : group_id
    //    ec : plan_id
    //    ed : o_time
    //    ee : o_type
    //    ef : f_step
    //    eg : p_times
    //    eh : s_type
    //    ei : remark_a
    //    ej : record_time
    //    ek : CREATE TABLE IF NOT EXISTS
    //    el :  (_id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
    //    em :  TEXT,
    //    en :  TEXT,
    //    eo :  TEXT,
    //    ep :   TEXT,
    //    eq :  TEXT,
    //    er :  TEXT,
    //    es :  TEXT,
    //    et :  TEXT,
    //    eu :  TEXT,
    //    ev :  TEXT,
    //    ew :  TEXT,
    //    ex :  TEXT,
    //    ey :  TEXT,
    //    ez :  TEXT,
    //    fA : referrer=
    //    fB : %3D
    //    fC : =
    //    fD : %26
    //    fE : &
    //    fF : ?
    //    fG : &
    //    fH : =
    //    fI : UTF-8
    //    fJ : 1
    //    fK : play.google.com
    //    fL : .apk
    //    fM : User-Agent
    //    fN : Location
    //    fO : http
    //    fP : ://
    //    fQ : :
    //    fR : ://
    //    fS : utf-8
    //    fT : details?
    //    fU : &id=
    //    fV : &
    //    fW : &
    //    fX : HttpRequestOffersTask
    //    fY : 2
    //    fZ : HttpTools
    //    fa : HttpExecutors
    //    fb : GET
    //    fc : User-Agent
    //    fd : RequestOnlineOffersTask
    //    fe : 1
    //    ff : 1
    //    fg : 2
    //    fh : my_natural
    //    fi : ref_
    //    fj : RedirectUtils
    //    fk : location.+[^'"]?(http[^'"\s]+)
    //    fl : location.+[^'"]?(market[^'"\s]+)
    //    fm : http-equiv=['|"]?refresh['|"]?.+(http[^'"\s]+)
    //    fn : http-equiv=['|"]?refresh['|"]?.+(market[^'"\s]+)
    //    fo : \{[^\}]+\}
        //     fp : FINAL_URL_ISNULL
        //     fq : market://
        //     fr : http.agent
        //     fs : 2
        //     ft : 2
        //     fu : 2
        //     fv : 1
        //     fw : 1
        //     fx : 3
        //     fy : 1
        //     fz : isinsted
        //     gA : nd
        //     gB : pd
        //     gC : af
        //     gD : igi
        //     gE : irt
        //     gF : inst
        //     gG : sr
        //     gH : cmd5
        //     gI : phead
        //     gJ : crs
        //     gK : ans
        //     gL : infos
        //     gM : 30a161c4b1bde4eea
        //     gN : data
        //     gO : shandle
        //     gP : 0
        //     gQ : pkey
        //     gR : zz2017
        //     gS : sign
        //     gT : 30a161c4b1bde4eea
        //     gU : android
        //     gV : tc
        //     gW : my_natural
        //     gX : 2
        //     gY : 1
        //     gZ : com.android.vending.INSTALL_REFERRER
        //     ga : pv
        //     gb : rqd
        //     gc : pk
        //     gd : ch
        //     ge : ua
        //     gf : gd
        //     gg : ud
        //     gh : co
        //     gi : ln
        //     gj : sn
        //     gk : sc
        //     gl : pn
        //     gm : cv
        //     gn : cn
        //     go : dn
        //     gp : so
        //     gq : nt
        //     gr : ss
        //     gs : rm
        //     gt : st
        //     gu : op
        //     gv : ro
        //     gw : cu
        //     gx : tz
        //     gy : m
        //     gz : cs
        //     hA : market://
        //     hB : CheckPlacementIdTask
        //     hC : pref_validate_placement_id
        //     hD : pref_key_validate_placement_id
        //     hE : res_status
        //     hF : resp_code
        //     hG : resp_msg
        //     hH : z
        //     hI : body
        //     hJ : 30a161c4b1bde4eea
        //     hK : infos
        //     hL : placement_id
        //     hM : placement_type
        //     hN : NaturalNewTask
        //     hO : res_status
        //     hP : body
        //     hQ : resp_code
        //     hR : z
        //     hS : rtime
        //     hT : 30a161c4b1bde4eea
        //     hU : 1
        //     hV : phead
        //     hW : pn
        //     hX : alk
        //     hY : bd
        //     hZ : value
        //     ha : referrer
        //     hb : HttpTools
        //     hc : isz
        //     hd : accept
        //     he : connection
        //     hf : Keep-Alive
        //     hg : POST
        //     hh : Content-Type
        //     hi : application/x-www-form-urlencoded
        //     hj : charset
        //     hk : utf-8
        //     hl : User-Agent
        //     hm : 1
        //     hn : WebLoader
        //     ho : http.agent
        //     hp : searchBoxJavaBridge_
        //     hq : accessibility
        //     hr : accessibilityTraversal
        //     hs : time out
        //     ht : redirect times bigger than max times!
        //     hu : url is null
        //     hv : onReceivedError:
        //     hw : http://market.android.com
        //     hx : https://market.android.com
        //     hy : https://play.google.com
        //     hz : http://play.google.com
        //     iA : pv
        //     iB : 7
        //     iC : ty
        //     iD : inds
        //     iE : itd
        //     iF : nd
        //     iG : tc
        //     iH : ps
        //     iI : cr
        //     iJ : tz
        //     iK : StrategyInfo
        //     iL : ac
        //     iM : at
        //     iN : 0
        //     iO : 0
        //     iP : 0
        //     iQ : 0
        //     iR : 0
        //     iS : 1
        //     iT : 1
        //     iU : 1
        //     iV : status
        //     iW : body
        //     iX : service_
        //     iY : service_24
        //     iZ : service_42
        //     ia : UTF-8
        //     ib : 30a161c4b1bde4eea
        //     ic : 30a161c4b1bde4eea
        //     id : data
        //     ie : pkey
        //     ig : sign
        //     ih : shandle
        //     ii : 0
        //     ij : pk
        //     ik : pkg
        //     il : ts
        //     im : co
        //     in : ch
        //     io : ud
        //     ip : gd
        //     iq : sn
        //     ir : sc
        //     is : st
        //     it : native
       //     iu : ir
       //     iv : ig
       //     iw : os
       //     ix : ln
       //     iy : i5
       //     iz : vc
       //     jA : isupblen
       //     jB : idys
       //     jC : blen
       //     jD : installtime
       //     jE : proxy
       //     jF : root
       //     jG : simulator
       //     jH : grt
       //     jI : 1
       //     jJ : dynamicsplicing
       //     jK : {gaid}
       //     jL : {android_id}
       //     jM : format
       //     jN : domain
       //     jO : preldutil
       //     jP : 1
       //     jQ : isprescrn
       //     jR : 0
       //     jS : openroute
       //     jT : 0
       //     jU : profcdsw
       //     jV : configs
       //     jW : cksw
       //     jX : 0
       //     jY : ckitv
       //     jZ : configs
       //     ja : service_44
       //     jb : service_72
       //     jc : group_id
       //     jd : plan_id
       //     je : configs
       //     jf : config_id
       //     jg : _
       //     jh : islocal
       //     ji : validtime
       //     jj : validtime
       //     jk : ,
       //     jl : offercount
       //     jm : offercachetime
       //     jn : dlswitch
       //     jo : flowcswitch
       //     jp : dlmtime
       //     jq : flowcroute
       //     jr : ulmtime
       //     js : maxmtime
       //     jt : sdreftime
       //     ju : sdrefintr
       //     jv : topapps
       //     jw : pdly
       //     jx : odly
       //     jy : isde
       //     jz : selfgrab
       //     kA : =
       //     kB : =
       //     kC : configs
       //     kD : sw
       //     kE : -
       //     kF : configs
       //     kG : swlock
       //     kH : 0
       //     kI : vwper
       //     kJ : StrategyServer
       //     kK : res_status
       //     kL : body
       //     kM : resp_code
       //     kN : z
       //     kO : 30a161c4b1bde4eea
       //     kP : req_id
       //     kQ : status
       //     kR : body
       //     kS : udt_tc
       //     kT : udt_tc
       //     kU : StrategyParamsFatory
       //     kV : phead
       //     kW : UTF-8
       //     kX : 30a161c4b1bde4eea
       //     kY : data
       //     kZ : shandle
       //     ka : domain_stat
       //     kb : domain_api2
       //     kc : domain_ploy
       //     kd : domain_an
       //     ke : domain_adx
       //     kf : domain_ac
       //     kg : domain_ustat
       //     kh : 1
       //     ki : 1
       //     kj : 1
       //     kk : -
       //     kl : 1
       //     km : =
       //     kn : =
       //     ko : =
       //     kp : &
       //     kq : =
       //     kr : &
       //     ks : =
       //     kt : 1
       //     ku : 1
       //     kv : 1
       //     kw : 1
       //     kx : -
       //     ky : [0-9a-zA-Z]{16}
       //     kz : &
       //     lA : AdSdkManager
       //     lB : [^0-9a-zA-Z_-]+
       //     lC : EtapLib
       //     lD : init failed,Context can't be null
       //     lE : Only letters(a-z,A-Z),characters(-,_) and numbers to setChannel.
       //     lF : AppKey is required
       //     lG : package
       //     lH : VIEW_SHOW
       //     lI : BannerView
       //     lJ : market://details?id=
       //     lK : #65AF3E
       //     lL : #ffffff
       //     lM : BannerView_isvisible =
       //     lN : #FFC62E
       //     lO : #88A6AAAF
       //     lP : sponsored
       //     lQ : translationX
       //     lR : #88A6AAAF
       //     lS : RectangleBannerView
       //     lT : market://details?id=
       //     lU : #000000
       //     lV : #65AF3E
       //     lW : #686868
       //     lX : BannerUtils
       //     lY : test
       //     lZ : translationY
       //     la : 0
       //     lb : pkey
       //     lc : zz2017
       //     ld : sign
       //     le : 30a161c4b1bde4eea
       //     lf : z
       //     lg : 0
       //     lh : pkg
       //     li : xd
       //     lj : pk
       //     lk : cv
       //     ll : loc
       //     lm : ln
       //     ln : e
       //     lo : d
       //     lp : u
       //     lq : ud
       //     lr : st
       //     ls : pv
       //     lt : ir
       //     lu : ig
       //     lv : com.android.vending
       //     lw : sc
       //     lx : md
       //     ly : tc
       //     lz : sv
       //     mA : req_id
       //     mB : rtime
       //     mC : rto
       //     mD : cto
       //     mE : z
       //     mF : body
       //     mG : 30a161c4b1bde4eea
       //     mH : offers_cache_time
       //     mI : infos
       //     mJ : stat
       //     mK : offers
       //     mL : no_fp
       //     mM : nlg
       //     mN : body
       //     mO : z
       //     mP : 30a161c4b1bde4eea
       //     mQ : stats
       //     mR : offers
       //     mS : infos
       //     mT : request_url
       //     mU : imp_url
       //     mV : click_route
       //     mW : display_style
       //     mX : weight
       //     mY : preload_cache_time
       //     mZ : error_def_click_route
       //     ma : translationY
       //     mb : translationY
       //     mc : translationY
       //     md : InternalBroadcastReceiver
       //     me : %d.png
       //     mf : %d.png
       //     mg : GET
       //     mh : PackageBroadcastReceive
       //     mi : android.intent.action.PACKAGE_ADDED
       //     mj : android.intent.action.PACKAGE_REMOVED
       //     mk : resp_code
       //     ml : resp_msg
       //     mm : req_id
       //     mn : offers_cache_time
       //     mo : res_status
       //     mp : resp_msg
       //     mq : 请求广告失败:
       //     mr : yyyy-MM-dd HH:mm:ss
       //     ms : resp_code
       //     mt : req_id
       //     mu : offers_cache_time
       //     mv : res_status
       //     mw : body
       //     mx : res_status
       //     my : resp_msg
       //     mz : resp_code
       //     nA : clickValid:
       //     nB : ,clickTime:
       //     nC : ,clickFrom:
       //     nD : camp_id
       //     nE : mobile_app_id
       //     nF : final_url
       //     nG : click_url
       //     nH : expired_time
       //     nI : AdClicked
       //     nJ : camp_id
       //     nK : click_time
       //     nL : install_callback_url
       //     nM : packagename
       //     nN : placement_id
       //     nO : click_url
       //     nP : preload_cache_time
       //     nQ : click_route
       //     nR : oid
       //     nS : error_def_click
       //     nT : statusCode
       //     nU : redirectUA
       //     nV : redirectUrl
       //     nW : redirectType
       //     nX : appid
       //     nY : co
       //     nZ : te
       //     na : pre_strategy
       //     nb : creatives
       //     nc : offer
       //     nd : camp_id
       //     ne : imp_url
       //     nf : click_url
      //      ng : click_callback_url
      //      nh : install_callback_url
      //      ni : mobile_app_id
      //      nj : icon
      //      nk : description
      //      nl : name
      //      nm : rate
      //      nn : store_rating
      //      no : installs
      //      np : size
      //      nq : recommend_mes
      //      nr : app_type
      //      ns : desc_button
      //      nt : View
      //      nu : thd_click_cb_urls
      //      nv : ,
      //      nw : thd_imp_cb_urls
      //      nx : ,
      //      ny : mAdCallToAction
      //      nz : View
      //      oA : mPlacementId required
      //      oB : ,
      //      oC : EtapLib
      //      oD : pls EtapNative.setAppKey and call EtapNative.initNativeAd
      //      oE : ,
      //      oF : req_ads_num
      //      oG : res_ads_num
      //      oH : creatives
      //      oI : ,
      //      oJ : req_ads_num
      //      oK : res_ads_num
      //      oL : creatives
      //      oM : ,
      //      oN : DomainManager
      //      oO : http://stat.hasmobi.net
      //      oP : http://adre.hasmobi.net
      //      oQ : http://stra.hasmobi.net
      //      oR : http://na.hasmobi.net
      //      oS : http://adx.hasmobi.net
      //      oT : http://det.hasmobi.net
      //      oU : https://hot.hasmobi.net
      //      oV : %s/log
      //      oW : %s/commonstat?pv=2
      //      oX : %s/commonstat
      //      oY : %s/native/v2/recommend
      //      oZ : %s/scene/v2/recommend
      //      oa : dp
      //      ob : opp
      //      oc : sbc
      //      od : camp_id
      //      oe : 0
      //      of : domains
      //      og : ,
      //      oh : NaturalResp{
      //      oi : statusCode=
      //      oj : , redirectUA='
      //      ok : , redirectType=
      //      ol : , redirectUrl='
      //      om : , pkg_name='
      //      on : , camp_id='
      //      oo : , co=
      //      op : , te=
      //      oq : , opp=
      //      or : , sbc=
      //      os : , dp=
      //      ot : , domains=
      //      ou : DownloadResult{
      //      ov : pkg='
      //      ow : , json='
      //      ox : , time=
      //      oy : BatMobiNativeAd
      //      oz : EtapLib
      //      pA : number
      //      pB : target_url
      //      pC : status_code
      //      pD : infos
      //      pE : phead
      //      pF : results
      //      pG : UrlDetector
      //      pH : UrlDetector
      //      pI : location.+[^'"]?(http[^'"\s]+)
      //      pJ : location.+[^'"]?(market[^'"\s]+)
      //      pK : http-equiv=['|"]?refresh['|"]?.+(http[^'"\s]+)
      //      pL : http-equiv=['|"]?refresh['|"]?.+(market[^'"\s]+)
      //      pM : \{[^\}]+\}
      //      pN : FINAL_URL_ISNULL
      //      pO : market://
      //      pP : http.agent
      //      pQ : ?
      //      pR : &
      //      pS : =
      //      pT : UTF-8
      //      pU : play.google.com
      //      pV : .apk
      //      pW : User-Agent
      //      pX : Location
      //      pY : http
      //      pZ : ://
      //      pa : %s/scene/v2/oemrecommend
      //      pb : %s/scene/v2/oemconfig
      //      pc : %s/native/local/recommend?isz=1
      //      pd : %s/api/v2/app?serviceid=1
      //      pe : %s/api/v2/app?serviceid=2
      //      pf : %s/api/cfg/v1?serviceid=1
      //      pg : %s/v4/api?serviceid=2
      //      ph : %s/v4/api?serviceid=1
      //      pi : %s/ads-dsp/api/v2/adx?serviceid=
      //      pj : %s/service/common?serviceid=1
      //      pk : %s/service/common?serviceid=2
      //      pl : UrlDetector
      //      pm : phead
      //      pn : UTF-8
      //      po : 30a161c4b1bde4eea
      //      pp : 30a161c4b1bde4eea
      //      pq : data
      //      pr : pkey
      //      ps : zz2017
      //      pt : shandle
      //      pu : 0
      //      pv : sign
      //      pw : android
      //      px : tc
      //      py : ads_id
      //      pz : oid
      //      qA : bb
      //      qB : cc
      //      qC : dd
      //      qD : ee
      //      qE : ff
      //      qF : gg
      //      qG : hh
      //      qH : ii
      //      qI : jj
      //      qJ : CREATE TABLE IF NOT EXISTS
      //      qK :  (_id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      //      qL :  TEXT,
      //      qM :  INTEGER,
      //      qN :  TEXT,
      //      qO :  TEXT,
      //      qP :  TEXT,
      //      qQ :  TEXT,
      //      qR :  INTEGER,
      //      qS :  INTEGER,
      //      qT :  TEXT,
      //      qU :  INTEGER)
      //      qV : table_c
      //      qW : aa
      //      qX : bb
      //      qY : cc
      //      qZ : dd
      //      qa : :
      //      qb : ://
      //      qc : utf-8
      //      qd : UrlDetector
      //      qe : res_status
      //      qf : resp_code
      //      qg : z
      //      qh : body
      //      qi : 30a161c4b1bde4eea
      //      qj : ce_type
      //      qk : ce_offers
      //      ql : ads_id
      //      qm : click_url
      //      qn : oid
      //      qo : UpdateObserver
      //      qp : 21
      //      qq : 24
      //      qr : 42
      //      qs : 44
      //      qt : 72
      //      qu : UpdateStategy
      //      qv : AntiCaptureTools
      //      qw : etap_
      //      qx : 5.0.4
      //      qy : table_a
      //      qz : aa
      //      rA : 30a161c4b1bde4eea
      //      rB : 30a161c4b1bde4eea
      //      rC : db_a.db
      //      rD : table_b
      //      rE : aa
      //      rF : bb
      //      rG : cc
      //      rH : dd
      //      rI : ee
      //      rJ : ff
      //      rK : gg
      //      rL : CREATE TABLE IF NOT EXISTS
      //      rM :  (_id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      //      rN :  TEXT,
      //      rO :  TEXT,
      //      rP :  TEXT,
      //      rQ :  TEXT,
      //      rR :  INTEGER,
      //      rS :  INTEGER,
      //      rT :  INTEGER)
      //      rU : su
      //      rV : /
      //      rW : /
      //      rX : PATH
      //      rY : :
      //      rZ : pversion
      //      ra : CREATE TABLE IF NOT EXISTS
      //      rb :  (_id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
      //      rc :  TEXT,
      //      rd :  TEXT,
      //      re :  INTEGER,
      //      rf :  TEXT)
      //      rg : offline_offers_respobj_json
      //      rh : DBManager
      //      ri : =
      //      rj : =
      //      rk : =
      //      rl :  ? and
      //      rm : =
      //      rn : =
      //      ro : <
      //      rp : =
      //      rq : =
      //      rr : =
      //      rs : =
      //      rt : =
      //      ru : dl
      //      rv : =
      //      rw : dl
      //      rx :  < ? and
      //      ry :  = ?
      //      rz : dl
      //      sA : is_root
      //      sB : is_gp_installed
      //      sC : latitude
      //      sD : s_click_route
      //      sE : gp_status
      //      sF : cmd5
      //      sG : read_external
      //      sH : creatives
      //      sI : ads_num
      //      sJ : inst
      //      sK : display_style
      //      sL : curpkgname
      //      sM : scene_type
      //      sN : placement_id
      //      sO : abid
      //      sP : phead
      //      sQ : crs
      //      sR : asn
      //      sS : crm
      //      sT : scr
      //      sU : infos
      //      sV : 30a161c4b1bde4eea
      //      sW : data
      //      sX : pkey
      //      sY : zz2017
      //      sZ : shandle
      //      sa : request_id
      //      sb : appkey
      //      sc : channel
      //      sd : ua
      //      se : adv_id
      //      sf : aid
      //      sg : local
      //      sh : lang
      //      si : sys_name
      //      sj : sys_code
      //      sk : pkg_name
      //      sl : cversion
      //      sm : cvname
      //      sn : sdk_name
      //      so : sdk_code
      //      sp : net_type
      //      sq : screen_size
      //      sr : ram
      //      ss : is_tablet
      //      st : operator
      //      su : rom
      //      sv : imei
      //      sw : imsi
      //      sx : cpu
      //      sy : mode
      //      sz : tz
      //      tA : etap_h5_cache_data
      //      tB : ,
      //      tC : ,
      //      tD : com.android.vending
      //      tE : market://details?id=
      //      tF : http://play.google.com/store/apps/details
      //      tG : https://play.google.com/store/apps/details
      //      tH : placement_id=
      //      tI : placement_id
      //      tJ : oid=
      //      tK : oid
      //      tL : ads_id_list=
      //      tM : ads_id_list
      //      tN : id=
      //      tO : id=
      //      tP : id=
      //      tQ : id=
      //      tR : http://
      //      tS : https://
      //      tT : http://
      //      tU : https://
      //      tV : ?id=
      //      tW : -
      //      tX : |

      //     tY : -
      //     tZ : |

      //     ta : 0
      //     tb : sign
      //     tc : 30a161c4b1bde4eea
      //     td : android
      //     te : cr
      //     tf : tc
      //     tg : ps
      //     th : sharedpreferences_etap_gp_downlaodntime
      //     ti : sharedpreferences_etap_local_recomend
      //     tj : sharedpreferences_etap_strategy_info
      //     tk : sharedpreferences_etap_strategy_recordtime
      //     tl : param_etap_gp_download_time
      //     tm : param_etap_gp_download_count
      //     tn : etap_offers_strategy_info
      //     to : etap_api_param_appkey
      //     tp : etap_api_param_channel
      //     tq : etap_api_param_adsnum
      //     tr : etap_api_param_downloadtype
      //     ts : etap_api_param_creatives
      //     tt : etap_api_param_first_app_version
      //     tu : etap_api_param_last_adoffer_index
      //     tv : etap_api_param_last_adoffer_nums
      //     tw : etap_api_ad_request_times
      //     tx : etap_api_ad_request_interval_time
      //     ty : etap_api_param_self_click_record
      //     tz : etap_api_param_302detect_record_time
      //     uA : images
      //     uB : icon_screen_image
      //     uC : banner_image_s
      //     uD : half_screen_image
      //     uE : banner_image_m
      //     uF : images
      //     uG : images
      //     uH : notify
      //     uI : content://downloads
      //     uJ : packageName
      //     uK : content://downloads/public_downloads/
      //     uL : PreOffersTask
      //     uM : 1
      //     uN : InterstitialActivity
      //     uO : hasStatics
      //     uP : placement_id
      //     uQ : mAd
      //     uR : #EA000000
      //     uS : market://details?id=
      //     uT : #65AF3E
      //     uU : hasStatics
      //     uV : placement_id
      //     uW : mAd
      //     uX : placement_id
      //     uY : etap_extra_ad
      //     uZ : ad_source
      //     ua : https://play.google.com/store/apps/details?id=
      //     ub : https://play.google.com/store/apps/details?id=
      //     uc : https?://.+\.googleusercontent\.com/
      //     ud : http://proxy.batmobi.net/
      //     ue : https?://.+\.ggpht\.com
      //     uf : MD5
      //     ug : UTF-8
      //     uh : http
      //     ui : https://
      //     uj : yyyy-MM-dd HH:mm:ss
      //     uk : GMT+8
      //     ul : ISO-8859-1
      //     um : ISO-8859-1
      //     un : MD5
      //     uo : MD5
      //     up : android.webkit.WebSettingsClassic
      //     uq : android.webkit.WebViewClassic
      //     ur : getUserAgentString
      //     |
      //     |\|
      //     ut : ;
      //     uu : icon_screen_image
      //     uv : banner_image_s
      //     uw : full_screen_image
      //     ux : half_screen_image
      //     uy : 桌面边缘停靠样式 【该样式功能暂时未提供】
      //     uz : icon_screen_image
      //     vA : 15555215556
      //     vB : 15555215558
      //     vC : 15555215560
      //     vD : 15555215562
      //     vE : 15555215564
      //     vF : 15555215566
      //     vG : 15555215568
      //     vH : 15555215570
      //     vI : 15555215572
      //     vJ : 15555215574
      //     vK : 15555215576
      //     vL : 15555215578
      //     vM : 15555215580
      //     vN : 15555215582
      //     vO : 15555215584
      //     vP : 000000000000000
      //     vQ : e21833235b6eef10
      //     vR : 012345678912345
      //     vS : 310260000000000
      //     vT : /dev/socket/qemud
      //     vU : /dev/qemu_pipe
      //     vV : /dev/socket/genyd
      //     vW : /dev/socket/baseband_genyd
      //     vX : goldfish
      //     vY : hasPipes
      //     vZ : hasGenyFiles
      //     va : dsp_click_callback_url
      //     vb : key_new
      //     vc : key_old
      //     vd : etap_extra_ad
      //     ve : UsablilityCheck
      //     vf : http.proxyHost
      //     vg : http.proxyPort
      //     vh : -1
      //     vi : SimulatorTools
      //     vj : tel:
      //     vk : 12345678910
      //     vl : generic
      //     vm : vbox
      //     vn : test-keys
      //     vo : google_sdk
      //     vp : Emulator
      //     vq : unknown
      //     vr : android
      //     vs : Android SDK built for x86
      //     vt : Genymotion
      //     vu : generic
      //     vv : google_sdk
      //     vw : android
      //     vx : /proc/net/tcp
      //     vy : \W+
      //     vz : 15555215554
      //     wA : log
      //     wB : batmobi.log
      //     wC : etap-1
      //     wa : /proc/tty/drivers
      //     wb : /proc/cpuinfo
      //     wc : hasQEmuDrivers
      //     wd : hasEmulatorBuild
      //     we : unknown
      //     wf : BOARD:
      //     wg : generic
      //     wh : BOARD:
      //     wi : generic
      //     wj : DEVICE:
      //     wk : sdk
      //     wl : MODEL:
      //     wm : sdk
      //     wn : PRODUCT:
      //     wo : goldfish
      //     wp : HARDWARE:
      //     wq : hasAdbInEmulator
      //     wr : ro.kernel.qemu
      //     ws : 1
      //     wt : hasQEmu
      //     wu : android.os.SystemProperties
      //     wv : get
      //     ww : .batmobi
      //     wx :

      //     wy : batmobi
      //     wz : MM/dd HH:mm:ss

}
